version: "3.8"
services:
  db:
    image: postgres:13
    volumes:
      - topicdb:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: internal
      POSTGRES_PASSWORD: modmailrules
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U internal"]
      interval: 10s
      timeout: 5s
      retries: 5

  internal_modmail:
    build: .
    volumes:
      - ./data:/data
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  topicdb:
